[package]
name = "nixtract"
version = "0.4.0"
authors = [
    "Erin van der Veen <nixtract@erinvanderveen.nl>",
    "Guillaume Desforges <guillaume.desforges@tweag.io>",
    "Dorran Howell <dorran.howell@tweag.io>",
    "Tweag I/O",
]
edition = "2021"
description = "A CLI tool and library to extract the graph of derivations from a Nix flake."
homepage = "github.com/tweag/nixtract"
repository = "https://github.com/tweag/nixtract"
license = "MIT OR Apache-2.0"
keywords = ["nix", "flake", "graph", "derivation"]
categories = ["development-tools"]
exclude = [
    "tests/**",
    "examples/**",
    "benches/**",
    "docs/**",
    "target/**",
    ".github/**",
]

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
clap-verbosity-flag = "3.0.4"
env_logger = "0.11.10"
flume = "0.12.0"
indicatif = "0.18.4"
indicatif-log-bridge = "0.2.3"
log = "0.4.29"
num_cpus = "1.17.0"
rayon = "1.12.0"
reqwest = { version = "0.13.3", features = ["blocking"] }
schemars = "1.2.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
shell-escape = "0.1.5"
tempfile = "3.27.0"
thiserror = "2.0.18"

[dev-dependencies]
pretty_assertions = "1.4.1"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
